// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkiServiceLogbook.Infrastructure.Data;

#nullable disable

namespace SkiServiceLogbook.Infrastructure.Migrations
{
    [DbContext(typeof(SkiServiceDbContext))]
    [Migration("20251209145238_InitialDomainInfrastructure")]
    partial class InitialDomainInfrastructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("SkiServiceLogbook.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValues")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValues")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("SkiServiceLogbook.Domain.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NextMatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SkiPair1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SkiPair2Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TestEventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TournamentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("WinnerSkiPairId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SkiPair1Id");

                    b.HasIndex("SkiPair2Id");

                    b.HasIndex("TestEventId");

                    b.HasIndex("WinnerSkiPairId");

                    b.HasIndex("TournamentName", "Round", "MatchNumber");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("SkiServiceLogbook.Domain.Entities.Ski", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("SkiPairId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SkiPairId", "Side");

                    b.ToTable("Skis");
                });

            modelBuilder.Entity("SkiServiceLogbook.Domain.Entities.SkiPair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PairNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PairNumber")
                        .IsUnique();

                    b.ToTable("SkiPairs");
                });

            modelBuilder.Entity("SkiServiceLogbook.Domain.Entities.TestEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AirTemperature")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Humidity")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnowCondition")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SnowTemperature")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventDate");

                    b.HasIndex("AirTemperature", "Humidity");

                    b.ToTable("TestEvents");
                });

            modelBuilder.Entity("SkiServiceLogbook.Domain.Entities.TestEventPair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MeasuredResult")
                        .HasPrecision(10, 3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Ranking")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkiPairId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TestEventId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SkiPairId");

                    b.HasIndex("TestEventId", "SkiPairId");

                    b.ToTable("TestEventPairs");
                });

            modelBuilder.Entity("SkiServiceLogbook.Domain.Entities.TestEventPairWax", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LayerOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TestEventPairId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WaxId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WaxId");

                    b.HasIndex("TestEventPairId", "LayerOrder");

                    b.ToTable("TestEventPairWaxes");
                });

            modelBuilder.Entity("SkiServiceLogbook.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SkiServiceLogbook.Domain.Entities.Wax", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MaxHumidity")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MaxTemperature")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MinHumidity")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MinTemperature")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SnowCondition")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("WaxCategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WaxCategoryId", "Name");

                    b.ToTable("Waxes");
                });

            modelBuilder.Entity("SkiServiceLogbook.Domain.Entities.WaxCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("WaxCategories");
                });

            modelBuilder.Entity("SkiServiceLogbook.Domain.Entities.WaxInstruction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conditions")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WaxInstructions");
                });

            modelBuilder.Entity("SkiServiceLogbook.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("SkiServiceLogbook.Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkiServiceLogbook.Domain.Entities.Match", b =>
                {
                    b.HasOne("SkiServiceLogbook.Domain.Entities.SkiPair", "SkiPair1")
                        .WithMany("MatchesAsSkiPair1")
                        .HasForeignKey("SkiPair1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SkiServiceLogbook.Domain.Entities.SkiPair", "SkiPair2")
                        .WithMany("MatchesAsSkiPair2")
                        .HasForeignKey("SkiPair2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SkiServiceLogbook.Domain.Entities.TestEvent", "TestEvent")
                        .WithMany("Matches")
                        .HasForeignKey("TestEventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SkiServiceLogbook.Domain.Entities.SkiPair", "WinnerSkiPair")
                        .WithMany("MatchesAsWinner")
                        .HasForeignKey("WinnerSkiPairId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SkiPair1");

                    b.Navigation("SkiPair2");

                    b.Navigation("TestEvent");

                    b.Navigation("WinnerSkiPair");
                });

            modelBuilder.Entity("SkiServiceLogbook.Domain.Entities.Ski", b =>
                {
                    b.HasOne("SkiServiceLogbook.Domain.Entities.SkiPair", "SkiPair")
                        .WithMany("Skis")
                        .HasForeignKey("SkiPairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SkiPair");
                });

            modelBuilder.Entity("SkiServiceLogbook.Domain.Entities.TestEventPair", b =>
                {
                    b.HasOne("SkiServiceLogbook.Domain.Entities.SkiPair", "SkiPair")
                        .WithMany("TestEventPairs")
                        .HasForeignKey("SkiPairId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkiServiceLogbook.Domain.Entities.TestEvent", "TestEvent")
                        .WithMany("TestEventPairs")
                        .HasForeignKey("TestEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SkiPair");

                    b.Navigation("TestEvent");
                });

            modelBuilder.Entity("SkiServiceLogbook.Domain.Entities.TestEventPairWax", b =>
                {
                    b.HasOne("SkiServiceLogbook.Domain.Entities.TestEventPair", "TestEventPair")
                        .WithMany("TestEventPairWaxes")
                        .HasForeignKey("TestEventPairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkiServiceLogbook.Domain.Entities.Wax", "Wax")
                        .WithMany("TestEventPairWaxes")
                        .HasForeignKey("WaxId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TestEventPair");

                    b.Navigation("Wax");
                });

            modelBuilder.Entity("SkiServiceLogbook.Domain.Entities.Wax", b =>
                {
                    b.HasOne("SkiServiceLogbook.Domain.Entities.WaxCategory", "WaxCategory")
                        .WithMany("Waxes")
                        .HasForeignKey("WaxCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WaxCategory");
                });

            modelBuilder.Entity("SkiServiceLogbook.Domain.Entities.SkiPair", b =>
                {
                    b.Navigation("MatchesAsSkiPair1");

                    b.Navigation("MatchesAsSkiPair2");

                    b.Navigation("MatchesAsWinner");

                    b.Navigation("Skis");

                    b.Navigation("TestEventPairs");
                });

            modelBuilder.Entity("SkiServiceLogbook.Domain.Entities.TestEvent", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("TestEventPairs");
                });

            modelBuilder.Entity("SkiServiceLogbook.Domain.Entities.TestEventPair", b =>
                {
                    b.Navigation("TestEventPairWaxes");
                });

            modelBuilder.Entity("SkiServiceLogbook.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");
                });

            modelBuilder.Entity("SkiServiceLogbook.Domain.Entities.Wax", b =>
                {
                    b.Navigation("TestEventPairWaxes");
                });

            modelBuilder.Entity("SkiServiceLogbook.Domain.Entities.WaxCategory", b =>
                {
                    b.Navigation("Waxes");
                });
#pragma warning restore 612, 618
        }
    }
}
